storage-type: mysql  # Choose between mysql, sqlite, mongodb
mysql:
  # If you choose mysql as your storage-type, fill out these details
  host: 127.0.0.1
  port: 3306
  database: punishments
  user: root
  password: ''
mongodb:
  # If you choose mongodb as your storage-type, fill out these details
  host: 127.0.0.1
  port: 27017
  database: punishments
  user: root
  password: ''
  authDatabase: admin  # The database to authenticate the user with

# This section is for configuring the /history menu
history-gui:
  title: "{player}'s History &7({page}/{maxpages})"
  rows-per-page: 3  # Must be between 1 and 5
  ban-icon: BARRIER
  mute-icon: FEATHER
  kick-icon: STICK
  next-page-icon: LIME_STAINED_GLASS_PANE
  previous-page-icon: LIME_STAINED_GLASS_PANE
  filler-icon: BLACK_STAINED_GLASS_PANE
  player-text:  # The text shown when hovering over the player head
    - "&6&n{player}"
    - " "
    - "&4Banned: &7{banned}"
    - "&dMuted: &7{muted}"
  next-page-text:
    - "&e&lNext Page --->"
  previous-page-text:
    - "&e&l<--- Previous Page"
  ban-text:
    - "&4Banned on: &7{start}"
    - "&4Banned until: &7{end}"
    - "&4Reason: &7{reason}"
  mute-text:
    - "&dMuted on: &7{start}"
    - "&dMuted until: &7{end}"
    - "&dReason: &7{reason}"
  kick-text:
    - "&cKicked on: &7{start}"
    - "&cReason: &7{reason}"

messages:
  default-reason: "N/A"  # The default ban/mute reason to use when none is provided
  user:
    banned: "&cYou are banned from joining the server for reason: &7{reason}"
    temp-banned: "&cYou are banned from joining the server for &7{time}&c for reason: &7{reason}"
    muted: "&cYou are muted for reason: &7{reason}"
    temp-muted: "&cYou are muted for &7{time}&c for reason: &7{reason}"
    unmuted: "&aYou have been unmuted!"
    kicked: "&cYou were kicked for reason: &7{reason}"
  admin:
    ban: "&cYou have permanently banned &7{player}&c!"
    ip-ban: "&cYou have permanently banned the IP &7{ip}&c!"
    temp-ban: "&cYou have banned &7{player}&c for &7{time}&c!"
    unban: "&cYou have unbanned &7{player}&c!"
    unban-ip: "&cYou have unbanned the IP &7{ip}&c!"
    mute: "&cYou have permanently muted &7{player}&c!"
    temp-mute: "&cYou have muted &7{player}&c for &7{time}&c!"
    unmute: "&cYou have unmuted &7{player}&c!"
    kick: "&cYou kicked &7{player}&c for reason: &7{reason}"
    already-banned: "&cPlayer &7{player}&c is already banned."
    already-ip-banned: "&cThe IP &7{ip}&c is already banned."
    already-muted: "&cPlayer &7{player}&c is already muted."
    wasnt-banned: "&cPlayer &7{player}&c is not currently banned."
    wasnt-ip-banned: "&cThe IP &7{ip}&c is not currently banned."
    wasnt-muted: "&cPlayer &7{player}&c is not currently muted."

misc:
  max-reason-length: 100  # Max characters for ban/mute/kick reason